export const sampleSentences = [
  "Purple elephants sing on Tuesdays, under the stairs.",
  "The toaster ran away with the spoon last summer—can you believe it?",
  "Flying pineapples dream of quiet beaches sometimes.",
  "Is a blanket happier than a rainbow in winter?!",
  "The spaghetti decided to go for a swim in the pond.",
  "Yesterday's coffee danced—with my slippers.",
  "He left his laughter on the roof, with the oranges.",
  "Can sandwiches really understand music?",
  "The moon slept in a hammock—made of cheese.",
  "Carrots enjoy reading books about galaxies!",
  "Why did the lamp sing to the refrigerator?",
  "Raindrops painted pictures on invisible paper.",
  "The clock decided to take a nap—at noon.",
  "Her shoes whispered secrets to the carpet.",
  "Tomorrow, the mountains might learn to dance.",
  "Socks have feelings about Tuesdays, don't they?",
  "The chair believes in dreams, and blue skies.",
  "A curious pencil jumped into the bathtub.",
  "The windows are planning a picnic on Mars.",
  "Bananas giggled at the sight of flying fish.",
  "Is it normal for teapots to feel emotions?",
  "The door argued with the mirror, about rainbows.",
  "Could a cupcake ever become a philosopher?",
  "The stars are writing a novel—about pinecones.",
  "The bicycle hummed a song to the parked cars.",
  "Do penguins have secret meetings at midnight?",
  "The ceiling laughed when the pillows danced.",
  "Would a cloud wear socks, if it could?",
  "The cactus sighed—thinking about the ocean.",
  "She heard the whispers of invisible apples.",
  "The refrigerator dreamed of snowy mountains.",
  "Can a spoon truly know happiness?",
  "The pillow decided to float away—at sunset.",
  "The shower sings lullabies to the shampoo bottles.",
  "Are the walls listening to our conversations?",
  "The flowerpot told jokes to the bookshelf.",
  "The sand thinks it’s a bird, soaring through time.",
  "Why did the tomato become an astronaut?",
  "The wind tickled the skyscrapers—with laughter.",
  "Clouds knit scarves for the distant hills.",
  "A solitary sock pondered the meaning of life.",
  "The trees are composing a song about stars.",
  "Could the toaster become friends with a snowflake?",
  "The shadows are planning a secret adventure.",
  "Will my blanket ever learn to fly?",
  "The alarm clock dreams of tropical vacations.",
  "The stairs asked the railing for directions.",
  "A spoon debated philosophy with the butter dish.",
  "The fridge told a bedtime story to the carrots.",
  "Did the mirror just wink at the sofa?",
];
